### ISSUE TITLE
Error using Laravel/Webpack

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [mrabbani/VueTypeahead#1]
ERROR in ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./~/vuejs-autocomplete/resources/assets/js/components/VueTypeahead.vue
Module build failed: SyntaxError: Unexpected token (117:24)

  
>117 |                     prefetch = {...prefetch, transform: this.transformer};
------------------------^

**Comment by mrabbani** [comment]
Delete `node_modules` and  run `npm install`.

**Comment by pippinsoft** [comment]
Is the problem here that the spread operator is only supported for arrays in ES6? It doesn't seem that it's providing much in the code.  Instead of:

```
prefetch = {...prefetch, transform: this.transformer};
```
why not just this:

```
prefetch.transform = this.transformer;
```

**Comment by mrabbani** [comment]
You are missing the Object rest spread transform:
https://babeljs.io/docs/plugins/transform-object-rest-spread/

One solution is

    npm install --save-dev babel-plugin-transform-object-rest-spread

and than create a `.babelrc` file in your project directory

    {
       "plugins": ["transform-object-rest-spread"]
    }

To know more  checkout  the [`issue of laravel mix`](https://github.com/JeffreyWay/laravel-mix/issues/76).

**Comment by YnievesDotNet** [comment]
I have this problem, and I do the recomendations, but continue same

**Comment by OmgImAlexis** [comment]
@mrabbani npmjs expects modules to use ES5 and handle all babel issues by publishing the built file instead of the source.

You shouldn't be telling users to setup babel for third party modules.

**Comment by adyz** [comment]
Same error here.

I think you can publish this with an folder that contains the transformed version of this (dist version)... I noticed yesterday that this packages has this optional import mode


https://github.com/Akryum/vue-observe-visibility#distribution-import
