### ISSUE TITLE
Event when input is cleared

### ISSUE THREAD

**Issue by kjfdebruin** [mrabbani/VueTypeahead#15]
After selecting an item, `v-on:selected` fires correctly. But then when the input is cleared, no events seem to be triggered.  I tried `v-on:blur` like you used in the example code, but it doesn't seem to trigger anything. I'm setting a variable when it is selected, and would like to clear it when the input is changed or cleared. How should this be handled?

I am passing a JSON object array to the component, and I'm using a custom template in case that changes anything.

**Comment by mrabbani** [comment]
`v-on:input` is fired when text is edited. `v-on:blur` is not supported in current version. But i will add this event in next version. Thanks a lot for this useful issue.

**Comment by kjfdebruin** [comment]
Thanks for the quick response and for a great component! `v-on:input` will work nicely.
