### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by ThomasRalee** [mrabbani/VueTypeahead#5]
Am facing Uncaught ReferenceError: $ is not defined, i believe its caused by this line of code:

````
 v-on:input="updateValue($event.target.value)"
````

````
imported the plugin like this:
import vueTypeahead from 'vuejs-autocomplete'
````

**Comment by ThomasRalee** [comment]
Solved it. Have to require jQuery for this to work.

**Comment by jpfong** [comment]
It works, I've added in my main.js

`// typeahead use jQuery
global.jQuery = require('jquery')
var $ = global.jQuery
window.$ = $`
